-- Adds CLIENT_INFORMATION_SUBMITTED to the notifications.type allow-list so
-- ClientInformationRequestService.submit() can create a notification carrying
-- the submitted request's real entity_id/action_url instead of being forced
-- to reuse the generic INFORMATION type (which is how the "click does
-- nothing" bug happened: INFORMATION notifications for this flow were
-- created with contractId as their only linking field, which is null for a
-- fresh client-info request).
--
-- Same non-destructive pattern as V44: rows already violating the new list
-- are normalized to INFORMATION rather than deleted, then the existing check
-- constraint (whatever its current name) is dropped and rebuilt with the
-- full value list plus the new type.

UPDATE notifications
SET type = 'INFORMATION'
WHERE type IS NULL OR type NOT IN (
    'SUCCESS', 'INFORMATION', 'WARNING', 'ERROR',
    'CONTRACT_CREATED', 'CONTRACT_SIGNED_AGENCY', 'QR_GENERATED',
    'CLIENT_OPENED_CONTRACT', 'CLIENT_SIGNED_CONTRACT', 'CONTRACT_FULLY_SIGNED',
    'PDF_GENERATED', 'CONTRACT_FINALIZED',
    'CONTRACT_QR_GENERATED', 'CONTRACT_CLIENT_SIGNED', 'CONTRACT_AGENCY_SIGNED',
    'CONTRACT_ACTIVATED', 'CONTRACT_COMPLETED', 'CONTRACT_CANCELLED',
    'RESERVATION_CREATED', 'RESERVATION_CONFIRMED', 'RESERVATION_CANCELLED',
    'RESERVATION_STARTING_SOON', 'RESERVATION_ENDING_SOON', 'RESERVATION_OVERDUE',
    'VEHICLE_CREATED', 'VEHICLE_STATUS_CHANGED', 'VEHICLE_AVAILABLE',
    'VEHICLE_RESERVED', 'VEHICLE_RENTED', 'VEHICLE_MAINTENANCE',
    'VEHICLE_DOCUMENT_EXPIRING', 'VEHICLE_INSURANCE_EXPIRING', 'VEHICLE_TECHNICAL_VISIT_EXPIRING',
    'MAINTENANCE_CREATED', 'MAINTENANCE_STARTED', 'MAINTENANCE_COMPLETED',
    'MAINTENANCE_CANCELLED', 'MAINTENANCE_DUE_SOON', 'MAINTENANCE_OVERDUE',
    'MAINTENANCE_STATUS_UPDATED', 'VEHICLE_BLOCKED_BY_MAINTENANCE',
    'PAYMENT_RECEIVED', 'PAYMENT_FAILED', 'PAYMENT_PARTIAL',
    'INVOICE_CREATED', 'INVOICE_OVERDUE', 'CLIENT_BALANCE_DUE',
    'TRIAL_STARTED', 'TRIAL_ENDING_SOON', 'TRIAL_EXPIRED',
    'SUBSCRIPTION_ACTIVATED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_PAYMENT_FAILED',
    'SUBSCRIPTION_CANCELLED', 'PLAN_UPGRADED', 'PLAN_DOWNGRADED',
    'SUBSCRIPTION_EXPIRES_SOON',
    'GPS_CONNECTED', 'GPS_DISCONNECTED', 'GPS_DEVICE_ONLINE', 'GPS_DEVICE_OFFLINE',
    'GPS_VEHICLE_MOVED', 'GPS_VEHICLE_LEFT_CITY', 'GPS_SPEED_ALERT', 'GPS_GEOFENCE_EXIT',
    'EMPLOYEE_CREATED', 'EMPLOYEE_DISABLED', 'EMPLOYEE_LOGIN', 'EMPLOYEE_PERMISSION_CHANGED',
    'LOGIN_FROM_NEW_DEVICE', 'PASSWORD_CHANGED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED',
    'EMAIL_VERIFIED', 'SUSPICIOUS_LOGIN_ATTEMPT',
    'BACKUP_COMPLETED', 'BACKUP_FAILED', 'SMTP_TEST_SUCCESS', 'SMTP_TEST_FAILED',
    'AI_QUOTA_EXCEEDED', 'FEATURE_LIMIT_REACHED',
    'ACCOUNT_INACTIVE', 'LOW_USAGE', 'UPGRADE_SUGGESTION',
    'SUPPORT_TICKET_CREATED', 'SUPPORT_TICKET_REPLY', 'SUPPORT_TICKET_STATUS_CHANGED',
    'CLIENT_INFORMATION_SUBMITTED'
);

DO $$
DECLARE
    constraint_name TEXT;
BEGIN
    FOR constraint_name IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'notifications'::regclass
          AND contype = 'c'
          AND pg_get_constraintdef(oid) ILIKE '%type%'
    LOOP
        EXECUTE format('ALTER TABLE notifications DROP CONSTRAINT IF EXISTS %I', constraint_name);
    END LOOP;
END $$;

ALTER TABLE notifications
ADD CONSTRAINT notifications_type_check
CHECK (type IN (
    'SUCCESS', 'INFORMATION', 'WARNING', 'ERROR',
    'CONTRACT_CREATED', 'CONTRACT_SIGNED_AGENCY', 'QR_GENERATED',
    'CLIENT_OPENED_CONTRACT', 'CLIENT_SIGNED_CONTRACT', 'CONTRACT_FULLY_SIGNED',
    'PDF_GENERATED', 'CONTRACT_FINALIZED',
    'CONTRACT_QR_GENERATED', 'CONTRACT_CLIENT_SIGNED', 'CONTRACT_AGENCY_SIGNED',
    'CONTRACT_ACTIVATED', 'CONTRACT_COMPLETED', 'CONTRACT_CANCELLED',
    'RESERVATION_CREATED', 'RESERVATION_CONFIRMED', 'RESERVATION_CANCELLED',
    'RESERVATION_STARTING_SOON', 'RESERVATION_ENDING_SOON', 'RESERVATION_OVERDUE',
    'VEHICLE_CREATED', 'VEHICLE_STATUS_CHANGED', 'VEHICLE_AVAILABLE',
    'VEHICLE_RESERVED', 'VEHICLE_RENTED', 'VEHICLE_MAINTENANCE',
    'VEHICLE_DOCUMENT_EXPIRING', 'VEHICLE_INSURANCE_EXPIRING', 'VEHICLE_TECHNICAL_VISIT_EXPIRING',
    'MAINTENANCE_CREATED', 'MAINTENANCE_STARTED', 'MAINTENANCE_COMPLETED',
    'MAINTENANCE_CANCELLED', 'MAINTENANCE_DUE_SOON', 'MAINTENANCE_OVERDUE',
    'MAINTENANCE_STATUS_UPDATED', 'VEHICLE_BLOCKED_BY_MAINTENANCE',
    'PAYMENT_RECEIVED', 'PAYMENT_FAILED', 'PAYMENT_PARTIAL',
    'INVOICE_CREATED', 'INVOICE_OVERDUE', 'CLIENT_BALANCE_DUE',
    'TRIAL_STARTED', 'TRIAL_ENDING_SOON', 'TRIAL_EXPIRED',
    'SUBSCRIPTION_ACTIVATED', 'SUBSCRIPTION_RENEWED', 'SUBSCRIPTION_PAYMENT_FAILED',
    'SUBSCRIPTION_CANCELLED', 'PLAN_UPGRADED', 'PLAN_DOWNGRADED',
    'SUBSCRIPTION_EXPIRES_SOON',
    'GPS_CONNECTED', 'GPS_DISCONNECTED', 'GPS_DEVICE_ONLINE', 'GPS_DEVICE_OFFLINE',
    'GPS_VEHICLE_MOVED', 'GPS_VEHICLE_LEFT_CITY', 'GPS_SPEED_ALERT', 'GPS_GEOFENCE_EXIT',
    'EMPLOYEE_CREATED', 'EMPLOYEE_DISABLED', 'EMPLOYEE_LOGIN', 'EMPLOYEE_PERMISSION_CHANGED',
    'LOGIN_FROM_NEW_DEVICE', 'PASSWORD_CHANGED', 'TWO_FACTOR_ENABLED', 'TWO_FACTOR_DISABLED',
    'EMAIL_VERIFIED', 'SUSPICIOUS_LOGIN_ATTEMPT',
    'BACKUP_COMPLETED', 'BACKUP_FAILED', 'SMTP_TEST_SUCCESS', 'SMTP_TEST_FAILED',
    'AI_QUOTA_EXCEEDED', 'FEATURE_LIMIT_REACHED',
    'ACCOUNT_INACTIVE', 'LOW_USAGE', 'UPGRADE_SUGGESTION',
    'SUPPORT_TICKET_CREATED', 'SUPPORT_TICKET_REPLY', 'SUPPORT_TICKET_STATUS_CHANGED',
    'CLIENT_INFORMATION_SUBMITTED'
));
