package com.carrental.service;

import com.carrental.entity.PlatformSettings;
import com.carrental.entity.TenantSettings;
import com.carrental.repository.PlatformSettingsRepository;
import com.carrental.repository.TenantSettingsRepository;
import com.carrental.util.EncryptionUtil;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.transaction.annotation.Transactional;

import java.util.Properties;

/**
 * Sends real email over SMTP using whichever provider is actually configured —
 * a tenant's own SMTP (from {@link TenantSettings}) if present, otherwise the
 * platform-wide SMTP configured by Super Admin (from {@link PlatformSettings}).
 *
 * <p>Email is always a best-effort side effect: callers receive a result
 * record instead of an exception so a failed send never breaks the business
 * operation (e.g. contract creation) that triggered it.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SmtpMailService {

    private final PlatformSettingsRepository platformSettingsRepository;
    private final TenantSettingsRepository tenantSettingsRepository;
    private final EncryptionUtil encryptionUtil;

    public record SmtpResult(boolean sent, String providerUsed, String errorMessage, String errorCode) {
        public static SmtpResult unconfigured() {
            return new SmtpResult(false, null, "No SMTP provider is configured.", "SMTP_NOT_CONFIGURED");
        }
        public static SmtpResult failure(String provider, String message, String code) {
            return new SmtpResult(false, provider, message, code);
        }
        public static SmtpResult success(String provider) {
            return new SmtpResult(true, provider, null, null);
        }
    }

    private record SmtpConfig(String host, int port, String username, String password,
                               boolean tls, String fromEmail, String label) {
    }

    /**
     * Sends using the tenant's own SMTP (falls back to platform SMTP).
     * Body is treated as HTML; a plain-text fallback is auto-generated by stripping tags.
     */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject, String body) {
        SmtpConfig config = resolveTenantConfig(tenantId);
        if (config == null) config = resolvePlatformConfig();
        return send(config, to, subject, body, null);
    }

    /**
     * Sends using the tenant's own SMTP with explicit HTML + plain-text bodies.
     */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject,
                                    String htmlBody, String plainBody) {
        SmtpConfig config = resolveTenantConfig(tenantId);
        if (config == null) config = resolvePlatformConfig();
        return send(config, to, subject, htmlBody, plainBody);
    }

    /**
     * Sends using the tenant's own SMTP with explicit HTML + plain-text bodies and a
     * single file attachment (e.g. the signed contract PDF).
     */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject,
                                    String htmlBody, String plainBody,
                                    String attachmentName, byte[] attachmentBytes, String attachmentContentType) {
        SmtpConfig config = resolveTenantConfig(tenantId);
        if (config == null) config = resolvePlatformConfig();
        return send(config, to, subject, htmlBody, plainBody, attachmentName, attachmentBytes, attachmentContentType);
    }

    /**
     * Sends using only the platform-wide SMTP.
     * Body is treated as HTML; plain-text fallback auto-generated.
     */
    @Transactional(readOnly = true)
    public SmtpResult sendPlatform(String to, String subject, String body) {
        return send(resolvePlatformConfig(), to, subject, body, null);
    }

    /**
     * Sends using only the platform-wide SMTP with explicit HTML + plain-text bodies.
     */
    @Transactional(readOnly = true)
    public SmtpResult sendPlatform(String to, String subject, String htmlBody, String plainBody) {
        return send(resolvePlatformConfig(), to, subject, htmlBody, plainBody);
    }

    /** Returns true if the platform SMTP is usable. */
    public boolean isPlatformConfigured() {
        return resolvePlatformConfig() != null;
    }

    // ── Core sender ───────────────────────────────────────────────────────────

    private SmtpResult send(SmtpConfig config, String to, String subject,
                            String htmlBody, String plainBody) {
        return send(config, to, subject, htmlBody, plainBody, null, null, null);
    }

    private SmtpResult send(SmtpConfig config, String to, String subject,
                            String htmlBody, String plainBody,
                            String attachmentName, byte[] attachmentBytes, String attachmentContentType) {
        if (config == null) {
            return SmtpResult.unconfigured();
        }
        if (!StringUtils.hasText(to)) {
            return SmtpResult.failure(config.label(), "Recipient email is required.", "EMAIL_NO_RECIPIENT");
        }
        try {
            JavaMailSenderImpl sender = new JavaMailSenderImpl();
            sender.setHost(config.host());
            sender.setPort(config.port());
            sender.setUsername(config.username());
            sender.setPassword(config.password());
            sender.setDefaultEncoding("UTF-8");

            Properties props = sender.getJavaMailProperties();
            props.put("mail.transport.protocol", "smtp");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable", String.valueOf(config.tls()));
            if (config.tls()) {
                props.put("mail.smtp.starttls.required", "true");
            }
            // Trust Zoho hosts (both standard + pro) so STARTTLS cert validation
            // does not fail when the tenant switches between them.
            props.put("mail.smtp.ssl.trust",
                    config.host().toLowerCase().contains("zoho")
                            ? "smtp.zoho.com smtppro.zoho.com"
                            : config.host());
            props.put("mail.smtp.connectiontimeout", "10000");
            props.put("mail.smtp.timeout", "10000");
            props.put("mail.smtp.writetimeout", "10000");

            boolean hasAttachment = attachmentBytes != null && attachmentBytes.length > 0 && StringUtils.hasText(attachmentName);

            MimeMessage message = sender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, hasAttachment, "UTF-8");
            helper.setTo(to);
            helper.setFrom(StringUtils.hasText(config.fromEmail()) ? config.fromEmail() : config.username());
            helper.setSubject(subject != null ? subject : "");

            boolean hasHtml  = StringUtils.hasText(htmlBody);
            boolean hasPlain = StringUtils.hasText(plainBody);

            if (hasHtml) {
                // Multipart/alternative: plain-text fallback first, HTML second
                String plain = hasPlain ? plainBody : stripHtml(htmlBody);
                helper.setText(plain, htmlBody);
            } else if (hasPlain) {
                helper.setText(plainBody, false);
            } else {
                helper.setText("(no content)", false);
            }

            if (hasAttachment) {
                helper.addAttachment(attachmentName, new org.springframework.core.io.ByteArrayResource(attachmentBytes),
                        StringUtils.hasText(attachmentContentType) ? attachmentContentType : "application/pdf");
            }

            sender.send(message);
            log.info("[SMTP] Sent via {} to {} | Subject: {}{}", config.label(), to, subject,
                    hasAttachment ? " | Attachment: " + attachmentName : "");
            return SmtpResult.success(config.label());
        } catch (Exception ex) {
            String errorCode = classifySmtpException(ex);
            log.warn("[SMTP] Send via {} to {} failed [{}]: {}", config.label(), to, errorCode, ex.getMessage());
            return SmtpResult.failure(config.label(), ex.getMessage(), errorCode);
        }
    }

    /** Strips HTML tags to produce a plain-text fallback for multipart emails. */
    private String stripHtml(String html) {
        if (html == null || html.isBlank()) return "";
        return html
                // Remove script and style blocks entirely
                .replaceAll("(?is)<(script|style)[^>]*>.*?</\\1>", "")
                // Convert common block elements to newlines
                .replaceAll("(?i)<br\\s*/?>", "\n")
                .replaceAll("(?i)</(p|div|tr|li|h[1-6])>", "\n")
                // Strip remaining tags
                .replaceAll("<[^>]+>", "")
                // Decode common HTML entities
                .replace("&nbsp;", " ")
                .replace("&amp;", "&")
                .replace("&lt;",  "<")
                .replace("&gt;",  ">")
                .replace("&quot;","\"")
                .replace("&#39;", "'")
                // Collapse excessive whitespace
                .replaceAll("[ \\t]+", " ")
                .replaceAll("\\n[ \\t]+", "\n")
                .replaceAll("\\n{3,}", "\n\n")
                .trim();
    }

    private String classifySmtpException(Exception ex) {
        String msg = ex.getMessage() != null ? ex.getMessage().toLowerCase() : "";
        String type = ex.getClass().getSimpleName().toLowerCase();
        if (type.contains("authentication") || msg.contains("535") || msg.contains("authentication")
                || msg.contains("auth") || msg.contains("credentials") || msg.contains("invalid login")
                || msg.contains("username and password not accepted") || msg.contains("invalid credentials")) {
            return "EMAIL_AUTH_FAILED";
        }
        if (msg.contains("tls") || msg.contains("ssl") || msg.contains("handshake")) {
            return "EMAIL_TLS_FAILED";
        }
        if (msg.contains("timeout") || msg.contains("timed out")) {
            return "EMAIL_PROVIDER_TIMEOUT";
        }
        if (msg.contains("unknown host") || msg.contains("nodename nor servname")
                || msg.contains("unreachable") || msg.contains("connection refused")
                || msg.contains("connect")) {
            return "EMAIL_PROVIDER_UNREACHABLE";
        }
        return "EMAIL_SEND_FAILED";
    }

    private SmtpConfig resolveTenantConfig(Long tenantId) {
        if (tenantId == null) return null;
        return tenantSettingsRepository.findByTenantId(tenantId)
                .filter(settings -> StringUtils.hasText(settings.getSmtpHost())
                        && StringUtils.hasText(settings.getSmtpUsername())
                        && settings.getSmtpPasswordEncrypted() != null)
                .map(settings -> new SmtpConfig(
                        settings.getSmtpHost(),
                        settings.getSmtpPort() != null ? settings.getSmtpPort() : 587,
                        settings.getSmtpUsername(),
                        encryptionUtil.decrypt(settings.getSmtpPasswordEncrypted()),
                        settings.getSmtpTls() == null || settings.getSmtpTls(),
                        settings.getSmtpUsername(),
                        "tenant SMTP"))
                .orElse(null);
    }

    private SmtpConfig resolvePlatformConfig() {
        return platformSettingsRepository.findAll().stream()
                .findFirst()
                .filter(settings -> StringUtils.hasText(settings.getSmtpHost())
                        && StringUtils.hasText(settings.getSmtpUsername())
                        && settings.getSmtpPasswordEncrypted() != null
                        // Treat null as enabled (backward-compatible with pre-V24 rows);
                        // explicit FALSE means the Super Admin deliberately disabled platform email.
                        && !Boolean.FALSE.equals(settings.getSmtpEnabled()))
                .map(settings -> new SmtpConfig(
                        settings.getSmtpHost(),
                        settings.getSmtpPort() != null ? settings.getSmtpPort() : 587,
                        settings.getSmtpUsername(),
                        encryptionUtil.decrypt(settings.getSmtpPasswordEncrypted()),
                        settings.getSmtpUseTls() == null || settings.getSmtpUseTls(),
                        StringUtils.hasText(settings.getFromEmail()) ? settings.getFromEmail() : settings.getSmtpUsername(),
                        "platform SMTP"))
                .orElse(null);
    }
}
