package com.carrental.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.transaction.annotation.Transactional;

/**
 * The one canonical email entry point — every feature (test email,
 * forgot-password, contract signing links, contract PDF notifications,
 * reservation/payment/trial notifications, support emails) calls this class,
 * never {@link HttpEmailProvider} directly.
 *
 * <p>All mail goes out through {@link HttpEmailProvider} (ZeptoMail's HTTPS
 * transactional email API, port 443) — SMTP is never attempted. Railway
 * blocks outbound SMTP ports (465/587) at the network level, so any SMTP
 * attempt there fails no matter how correctly it's configured; ZeptoMail's
 * HTTP API has no such restriction.
 *
 * <p>Email is always a best-effort side effect: callers receive a result
 * record instead of an exception so a failed send never breaks the business
 * operation (e.g. contract creation) that triggered it.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SmtpMailService {

    private static final String PROVIDER_LABEL = "ZEPTOMAIL";

    private final HttpEmailProvider httpEmailProvider;

    public record SmtpResult(boolean sent, String providerUsed, String errorMessage, String errorCode,
                              String exceptionClass) {
        public static SmtpResult unconfigured() {
            return new SmtpResult(false, null, "No email provider is configured.", "EMAIL_NOT_CONFIGURED", null);
        }
        public static SmtpResult failure(String provider, String message, String code) {
            return new SmtpResult(false, provider, message, code, null);
        }
        public static SmtpResult failure(String provider, String message, String code, String exceptionClass) {
            return new SmtpResult(false, provider, message, code, exceptionClass);
        }
        public static SmtpResult success(String provider) {
            return new SmtpResult(true, provider, null, null, null);
        }
    }

    /** Non-secret snapshot of the resolved email config — safe to log (never includes the API token). */
    public record PlatformSmtpDiagnostics(boolean configured, String source, String host, Integer port,
                                           boolean usernamePresent, String fromEmail, String fromName,
                                           boolean startTls, boolean passwordPresent) {
        public static PlatformSmtpDiagnostics none() {
            return new PlatformSmtpDiagnostics(false, "NONE", null, null, false, null, null, false, false);
        }
    }

    /** Describes the currently resolved ZeptoMail config for safe debug logging. */
    public PlatformSmtpDiagnostics describePlatformConfig() {
        return new PlatformSmtpDiagnostics(
                httpEmailProvider.isConfigured(),
                "ZEPTOMAIL_API",
                httpEmailProvider.baseUrl(),
                null,
                httpEmailProvider.tokenPresent(),
                httpEmailProvider.fromEmail(),
                httpEmailProvider.fromName(),
                false,
                httpEmailProvider.tokenPresent());
    }

    /**
     * Sends a message. {@code tenantId} is accepted for logging/context parity
     * with call sites but no longer selects a per-tenant SMTP config — every
     * send goes out through the single platform-wide ZeptoMail account.
     * Body is treated as HTML; a plain-text fallback is auto-generated by stripping tags.
     */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject, String body) {
        return send(to, subject, body, null, null, null, null);
    }

    /** Sends with explicit HTML + plain-text bodies. */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject,
                                    String htmlBody, String plainBody) {
        return send(to, subject, htmlBody, plainBody, null, null, null);
    }

    /** Sends with explicit HTML + plain-text bodies and a single file attachment (e.g. the signed contract PDF). */
    @Transactional(readOnly = true)
    public SmtpResult sendForTenant(Long tenantId, String to, String subject,
                                    String htmlBody, String plainBody,
                                    String attachmentName, byte[] attachmentBytes, String attachmentContentType) {
        return send(to, subject, htmlBody, plainBody, attachmentName, attachmentBytes, attachmentContentType);
    }

    /** Body is treated as HTML; plain-text fallback auto-generated. */
    @Transactional(readOnly = true)
    public SmtpResult sendPlatform(String to, String subject, String body) {
        return send(to, subject, body, null, null, null, null);
    }

    /** Sends with explicit HTML + plain-text bodies. */
    @Transactional(readOnly = true)
    public SmtpResult sendPlatform(String to, String subject, String htmlBody, String plainBody) {
        return send(to, subject, htmlBody, plainBody, null, null, null);
    }

    /** Returns true if ZeptoMail is usable (API token + from-email configured). */
    public boolean isPlatformConfigured() {
        return httpEmailProvider.isConfigured();
    }

    /** The active email provider — always ZeptoMail; safe to expose, no secrets. */
    public String activeProvider() {
        return PROVIDER_LABEL;
    }

    // ── Core sender ──────────────────────────────────────────────────────────

    private SmtpResult send(String to, String subject, String htmlBody, String plainBody,
                            String attachmentName, byte[] attachmentBytes, String attachmentContentType) {
        if (!StringUtils.hasText(to)) {
            return SmtpResult.failure(PROVIDER_LABEL, "Recipient email is required.", "EMAIL_NO_RECIPIENT");
        }
        // ZeptoMail's HTML-only send is fine, but keep the plain-text fallback
        // consistent with prior multipart behavior for HTML-only callers.
        String resolvedPlain = StringUtils.hasText(plainBody)
                ? plainBody
                : (StringUtils.hasText(htmlBody) ? stripHtml(htmlBody) : null);

        EmailMessage email = new EmailMessage(to, subject, htmlBody, resolvedPlain,
                attachmentName, attachmentBytes, attachmentContentType);
        return httpEmailProvider.send(email);
    }

    /** Strips HTML tags to produce a plain-text fallback for multipart emails. */
    private String stripHtml(String html) {
        if (html == null || html.isBlank()) return "";
        return html
                // Remove script and style blocks entirely
                .replaceAll("(?is)<(script|style)[^>]*>.*?</\\1>", "")
                // Convert common block elements to newlines
                .replaceAll("(?i)<br\\s*/?>", "\n")
                .replaceAll("(?i)</(p|div|tr|li|h[1-6])>", "\n")
                // Strip remaining tags
                .replaceAll("<[^>]+>", "")
                // Decode common HTML entities
                .replace("&nbsp;", " ")
                .replace("&amp;", "&")
                .replace("&lt;",  "<")
                .replace("&gt;",  ">")
                .replace("&quot;","\"")
                .replace("&#39;", "'")
                // Collapse excessive whitespace
                .replaceAll("[ \\t]+", " ")
                .replaceAll("\\n[ \\t]+", "\n")
                .replaceAll("\\n{3,}", "\n\n")
                .trim();
    }
}
