package com.carrental.dto.invoice;

import jakarta.validation.constraints.DecimalMin;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Request body for {@code POST /api/invoices} — create an invoice.
 *
 * <p>Two modes, distinguished by {@link #contractId}:
 * <ul>
 *   <li><b>Contract-linked</b> ({@code contractId} set): every other field is
 *       ignored — invoiceNumber, client, rental period, and amount are all
 *       derived from the contract itself (see InvoiceService#syncInvoiceForContract).
 *       This is also idempotent: calling it again for the same contract updates
 *       the existing invoice instead of creating a duplicate.</li>
 *   <li><b>Manual</b> ({@code contractId} null): the exceptional/ad-hoc case —
 *       client and dates must be supplied; either {@link #lines} (preferred —
 *       {@code total} is always recomputed server-side as quantity*unitPrice,
 *       never trusted from the client) or, for backward compatibility, a flat
 *       {@link #amount}. The invoice number is always generated by the backend
 *       (see NumberGeneratorService), never client-supplied.</li>
 * </ul>
 *
 * <p>Deliberately has no {@code status} field — status is never client-supplied
 * (see PaymentService#updateInvoiceStatus, the single place that computes it).
 */
@Data
public class CreateInvoiceRequest {

    /** When set, this is a contract-linked invoice — see class javadoc. */
    private Long contractId;

    private String clientName;

    private Long clientId;

    private LocalDate issueDate;

    private LocalDate dueDate;

    /** Manual mode, itemized (preferred). */
    private List<InvoiceLineDto> lines;

    @DecimalMin(value = "0", message = "Discount cannot be negative")
    private BigDecimal discountAmount;

    @DecimalMin(value = "0", message = "Tax cannot be negative")
    private BigDecimal taxAmount;

    /** Manual mode, legacy flat-amount fallback when {@link #lines} is not supplied. */
    @DecimalMin(value = "0.01", message = "Amount must be greater than zero")
    private BigDecimal amount;

    private String notes;
}
