package com.carrental.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * GPS alert generated by the tracking system.
 */
@Entity
@Table(
    name = "gps_alerts",
    indexes = {
        @Index(name = "idx_gps_alert_tenant", columnList = "tenant_id"),
        @Index(name = "idx_gps_alert_vehicle", columnList = "vehicle_id"),
        @Index(name = "idx_gps_alert_type", columnList = "alert_type"),
        @Index(name = "idx_gps_alert_read", columnList = "tenant_id, read")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GpsAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_type", nullable = false, length = 30)
    private GpsAlertType alertType;

    @Column(nullable = false, length = 255)
    private String message;

    @Column(length = 20)
    private String severity; // LOW, MEDIUM, HIGH, CRITICAL

    @Column
    private Boolean read = false;

    @Column(name = "vehicle_id")
    private Long vehicleId;

    @Column(name = "vehicle_name", length = 150)
    private String vehicleName;

    @Column(name = "latitude")
    private Double latitude;

    @Column(name = "longitude")
    private Double longitude;

    @Column(name = "speed")
    private Double speed;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    // ── Multi-tenancy link ──────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tenant_id", nullable = false)
    private Tenant tenant;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        if (read == null) {
            read = false;
        }
    }
}
